cilium/hive

cell/module.go
hive.go
hive_test.go
job/job.go
job/job_test.go

This allows having "optional" decorators that won't be called. This is primarily needed for providing a "job.Group" for each module without creating the group and adding it to the lifecycle if it is not used.

Add support for multiple module decorators

---

cell/cell.go
cell/config.go
cell/decorator.go
cell/group.go
cell/invoke.go
cell/lifecycle.go
cell/module.go
cell/provide.go
hive.go

Users of the library may not be interested to see a trace of every action
that the hive runs, but rather only log actions that take longer than a
specific threshold. Add an option that reduces the logging verbosity
based on how long the actions take.
Corresponds to https://github.com/cilium/cilium/pull/32033

hive: Add option to reduce trace logging

---

cell/cell.go
cell/config.go
cell/decorator.go
cell/group.go
cell/invoke.go
cell/module.go
cell/provide.go
example/main.go
hive.go
hive_test.go
hivetest/slog.go
job/job_test.go
job/observer_test.go
job/oneshot_test.go
job/timer_test.go

Instead of having to provide a logger already at hive creation time, pass the logger to Start/Stop/Run, which is when the underlying cells actually need it.
Also revert the changes to the Apply interface by passing the logger when the invokes are actually run instead of during apply.
Finally, add hivetest.Logger to create a logger from a testing.TB, so that the logs can be attributed to the correct test when running tests in parallel. Unfortunately, t.Helper() doesn't correctly work in combination with slog - we log the real source location as an attribute as a workaround.

hive: take Logger as part of Start/Stop or Run

---

cell/config.go
hive_test.go

This fixes and adds a regression test for a data race due to using a shared FlagSet in cell.Config that was mutated due to e.g. (*FlagSet).AddFlag modifying the passed in flag. This race occured in cases where a single Config cell was used in multiple hives in parallel (e.g. by tests).
```
Previous write at 0x00c000111ea0 by goroutine 10:
github.com/spf13/pflag.(*FlagSet).AddFlag()
/home/jussi/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:854 +0x153
```
The issue is fixed by creating the FlagSet during Apply() so each invocation gets its own unshared set.
Reported-by: David Bimmler <david.bimmler@isovalent.com>

Fix data race in cell.Config due to shared FlagSet

---

cell/invoke.go
cell/provide.go

Use slices.Sort instead of sort.Strings

---

job/metrics.go
job/timer.go
job/timer_test.go

The current Trigger implementation does not allow folding multiple requests over a time interval. In the cilium codebase, this feature is available in the "github.com/cilium/cilium/pkg/trigger" package (see https://github.com/cilium/cilium/pull/32973#discussion_r1633050869 as an example) but lacks the benefits of the hive integration.
The PR adds the ability to specify a debounce interval to a timer trigger. Doing so, multiple trigger requests over the debounce interval are folded and the trigger is called just once. A debouncing trigger can work with:
- a timer with a zero interval: in this case the job runs only when explicitly requested, through a call to its trigger
- a timer with a non-zero interval: in this case the job runs also when the internal timer ticks, and the trigger is …

job: Add debouncing trigger

---

job/job.go
job/job_test.go
job/observer.go
job/oneshot.go
job/timer.go

Adds validation for job.OneShot to match regex `^[a-z][a-z0-9_\-]{0,30}$`. It avoids construction of jobs that are not usable for metrics.

job: Validate job.OneShot name

---

hive.go

uber/dig defaults to checking for cycles on each Provide() call, which on large graphs becomes pretty expensive (cilium-agent is getting into multiple seconds now). To speed things up, set the DeferAcyclicVerification option on the dig container (cycles are checked on each Invoke).
Here's the effect on TestAgentCells in cilium/cilium:
Before:
```
daemon/cmd$ go test . -test.run TestAgentCell -test.count 1
ok      github.com/cilium/cilium/daemon/cmd     3.674s
```
After:
```
daemon/cmd$ go test . -test.run TestAgentCell -test.count 1
ok      github.com/cilium/cilium/daemon/cmd     0.192s
```

Use DeferAcyclicVerification()

---

job/job.go
job/observer.go
job/oneshot.go
job/timer.go

Increasing the job name length from 30 characters to 100 to accommodate lon names for jobs. This includes the StateDB Reflectors, the job names for that have a table name of 30 characters and also the job name and the prefix.

Bump max job name length

---

job/job.go
job/job_test.go
job/observer.go
job/oneshot.go
job/timer.go

The job names may come from many different sources and it is too much of a foot-gun to reject the names by panicing.
Instead to keep the names within a nice constraint set of characters and length, sanitize the names silently.
Related PR that had to work around the panics:
https://github.com/cilium/cilium/pull/35031

job: Sanitize instead of validate the job names

---

cell/lifecycle.go
cell/lifecycle_test.go

Adds a constructor for the DefaultLifecycle which allows to specify the current state of the appended hooks.
Includes a safe check if attempted to start the same lifecycle multiple times.

lifecycle: Adds DefaultLifecycle constructor

---

example/events.go
script.go
script/README.md
script/cmds.go
script/engine.go
script/makeraw_unix.go
script/makeraw_unix_bsd.go
script/makeraw_unix_other.go
script/makeraw_unsupported.go
script/state.go

This adds the ability to interrupt long-running commands. This is needed to implement something like "db watch table" that watches a table for changes until interrupted with ctrl-c.
See commits for more details.
You can try this out with:
```
go run ./example repl
> hive start
> events
```

script: Add support for interrupts

---

script/scripttest/scripttest.go
script/scripttest/scripttest_test.go

To allow cleaning up resources after the test terminates, pass the testing.TB to the newEngine function.
This is needed to be able to stop the hive in a test:
```
scripttest.Test(...,
func(t testing.TB) *script.Engine {
h := hive.New(Thing)
require.NoError(t, h.Start(...))
t.Cleanup(func() {
assert.NoError(t, h.Stop(...))
})
return &script.Engine{...}
}, ...)
```

scripttest: Pass testing.TB to newEngine

---

script/cmds.go
script/engine.go
script/scripttest/scripttest.go
script/scripttest/scripttest_test.go
script/scripttest/testdata/basic.txt
script/state.go

script: Add '*' prefix for retrying commands
This adds a generic facility for retrying failing commands.
A command that is prefixed with '*' and fails will cause the whole section (delimited by '#' comments) to be retried from the top.
Retrying is repeated until the command succeeds or the context is cancelled. The retry interval can be set in (*Engine).RetryInterval.
Example usage:
```
db show -o=out.table my-table
* cmp out.table expected.table
```
---
script: Add -scripttest.update to update txtar files
To make it easy to create and update expected test outputs, add the
-scripttest.update flag which updates the txtar files with the 'cmp'
inputs.
To allow waiting for the inputs to reach expected state, add the '!*'
prefix for retrying until failure, e.g. to allow writing:
```
db show …
```

script: Add '*' and '!*' prefixes for retrying commands and -scripttest.update for updating files

---

cell/cell.go
cell/config.go
cell/decorator.go
cell/group.go
cell/invoke.go
cell/module.go
cell/provide.go
hive.go
hive_test.go

Add the ability to decorate a type in all scopes. This is sometimes useful when one needs to swap out a value or implementation coming from a cell that one doesn't control.

cell: Add DecorateAll for decorating everywhere

---

script.go

When newBPFReconciler is not enabled, it return an empty ScriptCmd. Which cause `cilium shell help` panic.
https://github.com/cilium/cilium/blob/21ad13700b0f295e4997ffe4d204a9dbcd4cf309/pkg/loadbalancer/experimental/bpf_reconciler.go#L48-L51
```
PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 1947 [running]:
github.com/cilium/cilium/daemon/cmd.shell.handleConn.func2()
/go/src/github.com/cilium/cilium/daemon/cmd/shell.go:117 +0x78
panic({0x36dd600?, 0x706ef80?})
/usr/local/go/src/runtime/panic.go:785 +0x124
github.com/cilium/hive/script.(*Engine).ListCmds(0x40004f6b00, {0x4689a00, 0x400045ae00}, 0x0, {0x0?, 0x4c?, 0x4003a55768?})
/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/script/engine.go:770 +0x104 …
```

[fix] skip empty command

---

example/main.go
hive.go

Currently, when starting the hive in cilium-agent we emit a log line:
2024-11-28T15:29:27.262458836Z time=2024-11-28T15:29:27Z level=info msg=Starting
which isn't particularly useful. Change it to mention the hive, so its a bit more informative.

Change hive startup message

---

script/cmds.go
script/engine.go
script/scripttest/testdata/basic.txt

'help some-unknown-command' crashed as ListCmds wasn't checking if the command was actually found from the commands map.
While at it, make the 'help' a bit more useful by allowing filtering of commands with a regexp.

script: Fix crash when help called with unknown command

---

script/cmds.go
script/engine.go
script/scripttest/testdata/basic.txt

The stdout and stderr commands already existed, and my change to grep to allow searching stdout was buggy, so revert this.
The second commit fixes a panic on "help some-unknown-command" (https://github.com/cilium/cilium/pull/35918)

script: Revert buggy change to grep command

---

script/cmds.go
script/scripttest/testdata/sed.txt

The simple 'replace' command falls short in situations where the input text isn't fully known, but still needs to be sanitized in some way. Instead of having to use e.g. the system 'sed' command, implement a very simple built-in version.

script: Implement simple "sed" command

---

script/cmds.go
script/engine.go
script/scripttest/testdata/basic.txt
script/scripttest/testdata/help.txt
script/state.go

Embed the pflag FlagSet into the command creation so we can show decent help for the flags.
The `CmdUsage` now contains a `Flags` field of type `func(*pflag.FlagSet)` (similar to `cell.Flagger`!) that
allows registering the flags. These flags are then shown in the help summary, e.g.
`[-q] [--quiet]` for `fs.BoolP("quiet", "q", ...)` and also expanded in the verbose help.
For example `help` now looks like:
```
> help
...
sleep duration [&]
sleep for a specified duration
stderr [-q] [--count=int] [--quiet] 'pattern'
find lines in the stderr buffer that match a pattern
stdout [-q] [--count=int] [--quiet] 'pattern'
find lines in the stdout buffer that match a pattern
stop [msg]
stop execution of the script
...
> help stdout
stdout [-q] [--count=int] [--quiet] 'pattern'
find lines in the …
```

script: Use pflag for command arguments

---

script/engine.go
script/scripttest/scripttest_test.go
script/scripttest/testdata/retry.txt

Since the parsing of the flags overwrite 'cmd.args' this caused the retry of the command to lose the flags. Keep the original args to the side and use those when parsing the arguments.

script: Do not lose flags when retrying command

---

script/engine.go

The origArgs wasn't set when executing via shell causing all arguments to disappear in interactive use.

script: Set origArgs also in ExecuteLine

---

cell/config.go
cell/config_test.go

When a hive declares the same configuration multiple times, only one of
them will take effect. In order to prevent resultant bugs, instead
detect and prevent such configuration in the first place.

cell: Fail hive configuration on duplicate flags

---

hive.go

Make the messages a bit more specific by mentioning hive, so they can be easily attributed. Follow-up to commit af5052cfd6d4 ("Change hive startup message").

Mention hive in start/stop info logs

---

cell/info.go
cell/lifecycle.go
command.go
hive.go
hivetest/lifecycle.go
script.go
script_test.go

The 'hive' command now prints objects. The 'hive start' and 'hive stop' are kept for backwards compatibility.
'hive/start' and 'hive/stop' are added to reflect the new style (flat commands, no sub-commands, thus better help).

Rework hive script commands

---

script/engine.go
script/scripttest/scripttest_test.go

It's easy to get pretty spammy logs when failing retried commands. We don't expect the need to retry many times in successful tests, so add an exponential backoff to make the output more reasonable on failures.

script: Exponential backoff for retrying

---

script/cmds.go
script/engine.go
script/state.go

* Use the default retry intervals if they're zero
* Require at least one retry before taking the output with `-scripttest.update`

script: Retry related fixes

---

script/engine.go
script/scripttest/scripttest_test.go

Fix lack of newline on retried command in logs and show the amount of time it took until retries succeeded.
Before:
```
scripttest.go:72: # Test command retrying and the flag parsing when retrying.
scripttest.go:72:  (0.010s)
(command "* retrytest --not-empty=xyz abc" failed, retrying in 10ms...)
(command "* retrytest --not-empty=xyz abc" succeeded after 1 retries)
--- PASS: TestAll/retry (0.01s)
```
After:
```
scripttest.go:72: # Test command retrying and the flag parsing when retrying.
> * retrytest --not-empty=xyz abc
retrytest called
scripttest.go:72: (command "* retrytest --not-empty=xyz abc" failed, retrying in 10ms...)
retrytest called
scripttest.go:72: (command "* retrytest --not-empty=xyz abc" succeeded after 1 retries in 0.010s)
--- PASS: TestAll/retry (0.01s)
```

script: Fix lack of newline on retried command in logs

---

cell/invoke.go
command.go
hive.go
script.go

Show the pretty-printed error from populating the object graph in PrintObjects() and PrintDotGraph(). Add the ErrPopulate so we can add special casing for it in cilium/cilium to also do the pretty-printing of the error there.
Will look like this instead of just being a one-liner:
```
Failed to populate object graph:
could not build arguments for function "github.com/cilium/cilium/daemon/cmd".configureAPIServer
/home/jussi/go/src/github.com/cilium/cilium/daemon/cmd/cells.go:330:
failed to build *server.Server:
could not build arguments for function "github.com/cilium/cilium/api/v1/server".newForCell
/home/jussi/go/src/github.com/cilium/cilium/api/v1/server/server.go:206:
failed to build *restapi.CiliumAPIAPI:
could not build arguments for function …
```

Improve error reporting for Populate()

---

job/job.go

Jobs can be added to a job group both before and after it has started. When adding a job group before it has started it is put in a queue and started on group start.
One of the parameters we pass in when the job starts is a health reporter. However, there was a bug where when you create a scoped job group, we would pass the health reporter of its parent to the job and not the health reporter of the scoped job group. We were doing it correctly for jobs added to the job group after it had started.
This commit fixes the bug enqueueing the health reporter along with the job when enqueueing before the job group has started and using the colocated health reporter to call the job on start.

job: Assign scoped health to jobs added to scoped job groups

---

script/cmds.go
script/scripttest/testdata/empty.txt

Simple command that checks if file or output streams are empty.
This provides quality-of-life improvement over having to define a empty file and 'cmp' against that.

script: add empty command.

---

cell/config.go
go.mod
go.sum

The github.com/mitchellh/mapstructure package is archived and no longer receives updates[^1]. The "blessed" fork[^2] is github.com/go-viper/mapstructure. The API is the same, so nothing needs to be changed apart from the import path.
[^1]: https://github.com/mitchellh/mapstructure/issues/349
[^2]: https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc

cell: migrate to github.com/go-viper/mapstructure/v2

---

cell/config.go
go.mod
go.sum

Reverts cilium/hive#49
The "go-viper/mapstructure/v2" is not compatible with "mitchellh/mapstructure":
```
--- FAIL: TestNodeAddressWhitelist (0.01s)
--- FAIL: TestNodeAddressWhitelist/v4-v6_mix (0.00s)
logger.go:256: time=2025-05-22T16:44:34.236+02:00 level=ERROR source=/home/jussi/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/cell/invoke.go:52 msg="Invoke failed" error="failed to unmarshal config struct tables.NodeAddressConfig: decoding failed due to the following error(s):\n\nerror decoding 'nodeport-addresses[0]': netip.ParsePrefix(\"2001::/16,10.0.0.0/8\"): ParseAddr(\"2001::/16,10.0.0.0\"): each colon-separated field must have at least one digit (at \"/16,10.0.0.0\").\nHint: field 'FooBar' matches flag 'foo-bar', or use tag `mapstructure:\"flag-name\"` to match …
```

Revert "cell: migrate to github.com/go-viper/mapstructure/v2"

---

script/cmds.go
script/engine.go
script/state.go

Add an additional safeguard to -scripttest.update when used with 'cmp' to ignore empty files and increase the retries to 2. This significantly increases the likelyhood that we do not pick a too "early" version of the actual output.
Removed the update handling from 'empty' command as I don't see a use-case where we'd use 'empty' on a file within the txtar. You can just empty the file manually.

script: Refuse empty files in cmp when updating

---

script/scripttest/scripttest.go

We still have global variables in cilium/cilium and tests that end up touching those will need to be run sequentially. To make this easier to orchestrate without having to e.g. use a mutex inside 'newEngine' add the 'NoParallel' option.
We are not making parallelism opt-in as we really want this to be the default way we run tests.

scripttest: Add NoParallel option

---

hive.go
hive_test.go

This change introduces functional options to `hive.Run()`, which resolve a limitation where, if `hive.NewWithOptions()` was called before flag parsing, the default *Options* (e.g. `StartTimeout` and `StopTimeout`) could not be dynamically configured. New options passed to `hive.Run()` now explicitly override the options set during `hive` initialization.
Corresponds to https://github.com/cilium/cilium/issues/41857.

hive: Enable runtime option overriding in hive.Run()
